### ISSUE TITLE
how to create this cool demo

### ISSUE THREAD

**Issue by JunMa11** [sczhou/Upscale-A-Video#2]
Hi @sczhou ,

Thanks for sharing the awesome work.

I have an awkward question: how did you create this kind of demo? Is there any out-of-the-box tool?

https://twitter.com/i/status/1734468279123775859

**Comment by kakeelee** [comment]
hi @JunMa11 , i'm looking for this kind of tools too, have you get some ? :-)

**Comment by 6drf21e** [comment]
> Hi @sczhou ,
> 
> Thanks for sharing the awesome work.
> 
> I have an awkward question: how did you create this kind of demo? Is there any out-of-the-box tool?
> 
> https://twitter.com/i/status/1734468279123775859

You can find the source code on this page: https://shangchenzhou.com/projects/upscale-a-video/

**Comment by JunMa11** [comment]
Hi @6drf21e ,

Where is the source code?

**Comment by JunMa11** [comment]
Hi @kakeelee , 

we create a demo here: https://github.com/bowang-lab/U-Mamba/blob/main/assets/create_visualization_video.py
